__author__ = 'netanel'

# MINIMAL PWM VALUE in uS - controls maximum movement in one side of the SERVO motors
SERVO_MINIMAL_POSITION = 800
SERVO_MAXIMAL_POSITION = 2200
SERVO_GRADUAL_MOVEMENT_STEP = int((SERVO_MAXIMAL_POSITION - SERVO_MINIMAL_POSITION) / 20)
SERVO_GRADUAL_MOVEMENT_DELAY = 0.05

# DC motor PWM configurations
DC_MOTOR_PWM_FREQUENCY = 100
DC_MOTOR_MINIMAL_DUTYCYCLE = 50
DC_MOTOR_MAXIMAL_DUTYCYCLE = 250